Repository pieces-app/example-typescript, pull requests merged in 2023-11, with the labels that each got.

#2 Update: @1.0.0 New Endpoint Examples & Expanded API Usage with UI
  package.json
  src/index.tsx
  tsconfig.json
Labels: enhancement

#5 Readme updates with new Examples + TOC Restructure
  README.md
Labels: documentation

#15 Contributor guide
  CONTRIBUTING.md
Labels: documentation

#17 Segment application functionality into separate files
  .DS_Store
  src/app/App.tsx
  src/app/components/Asset.tsx
  src/app/components/Button.tsx
  src/app/components/Header.tsx
  src/app/components/Indicator.tsx
  src/app/components/TextInput.tsx
  src/app/utils/Connect.tsx
  src/index.tsx
Labels: project structure

#18 Create Issue & PR templates
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: project structure, templates

#20 Merge pull request #16 from pieces-app/sophyia
  .DS_Store
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  src/app/App.tsx
  src/app/components/Asset.tsx
  src/app/components/Button.tsx
  src/app/components/Header.tsx
  src/app/components/Indicator.tsx
  src/app/components/TextInput.tsx
  src/app/utils/Connect.tsx
  src/index.tsx
Labels: enhancement

#23 Sophyia
  assets/mockups/design_contributing.md
  assets/mockups/django-testing-docs-readthedocs-io-en-latest.pdf
Labels: project structure

#22 add ability to select list and rename/delete based on selection
  src/app/App.tsx
  src/app/components/TextInput.tsx
Labels: enhancement

#27 @pieces.app/client --> @pieces.app/pieces-client-os naming in readme + references throughout the project
  README.md
  package.json
  src/app/App.tsx
  src/app/components/Asset.tsx
  src/app/components/Button.tsx
  src/app/utils/Connect.tsx
Labels: maintenance
