Repository pieces-app/example-typescript, pull requests merged in 2023-12, with the labels that each got.

#28 added installation process for nvm
  README.md
Labels: maintenance

#34 added ts and react
  package.json
Labels: maintenance

#36 Downgraded typescript from @>5 --> @<5 as reactscripts@5.0.1 requires typescript@^4
  package.json
Labels: maintenance

#35 WIP: @pythonisticals UI Update PR Rework with Notes
  public/index.html
  src/app/App.tsx
  src/app/components/Button.tsx
  src/app/components/Header.tsx
  src/app/components/Indicator.tsx
  src/app/components/TextInput.tsx
  src/app/icons/check.png
  src/index.tsx
Labels: enhancement, community review

#51 WIP: Copilot Example
  package.json
  src/app/App.tsx
  src/app/components/Copilot.tsx
  src/app/components/Header.tsx
  src/app/components/Indicator.tsx
  src/app/components/TextInput.tsx
  src/app/controllers/copilotStreamController.tsx
Labels: enhancement, new endpoint

#45 Create build-test.yml
  .github/workflows/build-test.yml
Labels: maintenance, pending review
