Repository pieces-app/example-typescript, pull requests merged in 2024-02, with the labels that each got.

#75 Update global.css
  src/app/global.css
Labels: enhancement, css styling

#80 updated--example-ts--to--example-typescript
  CONTRIBUTING.md
  package.json
Labels: enhancement, good first issue

#76 feat: Added You're connected Button animation
  src/app/components/Indicator/Indicator.tsx
  src/app/components/Indicator/indicator.css
Labels: enhancement, css styling

#82 Updates to order of operations and accurate steps in the readme for creating a project
  README.md
Labels: documentation, enhancement, community review

#83 fix: Refactor Inline Styles of App.tsx to global.css
  src/app/App.tsx
  src/app/components/Copilot/Copilot.tsx
  src/app/global.css
Labels: bug, enhancement, css styling

#86 fix : Implemented Search Function using `SearchApi`
  src/app/App.tsx
  src/app/global.css
Labels: new endpoint, community review

#87 SDK version bump --> 2.0.0-2, new clean-m + clean-w commands
  package.json
Labels: enhancement
